sudo: required

dist: xenial
addons:
  apt:
    update: true

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install --upgrade pip
  - pip install cython

install:
  - pip install -r requirements.txt

script:
  - python test/test_load_traj.py
